---
project_name: go-service-boilerplate
before:
  hooks:
    - go mod tidy
builds:
  - id: service
    env:
      - CGO_ENABLED=0
    main: ./cmd/main.go
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: ./container/arm.Dockerfile
    skip_push: false
    image_templates:
      - 'maniacoder/oss-go-service-boilerplate:{{ .Version }}'
      - 'maniacoder/oss-go-service-boilerplate:latest'
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
snapshot:
  name_template: "{{ .Tag }}-next"
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^*.md:'
